### ISSUE TITLE
is this build supposed to run from the e10 straight up?

### ISSUE THREAD

**Issue by angrydexterous** [synapse-wireless/meta-synapse#12]
Or do I need to select a different machine type? Base build constructs a kernel for at91sam9m10g45ek  at91sam9x5ek instead of at91sam9g20ek

No at91sam9g20ek machine type avail though, is it just a matter of selecting a different kernel?

**Comment by angrydexterous** [comment]
kernel no boot. black screen.
would uboot version matter?

```
Bytes transferred = 2143528 (20b528 hex)
Automatic boot of image at addr 0x21000000 ...
## Booting kernel from Legacy Image at 21000000 ...
   Image Name:   Linux-3.10.0-custom
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    2143464 Bytes =  2 MB
   Load Address: 20008000
   Entry Point:  20008000
   Verifying Checksum ... OK
   Loading Kernel Image ... OK
OK

Starting kernel ...

Uncompressing Linux... done, booting the kernel.    
```

and hangs

**Comment by angrydexterous** [comment]
sorry for the spam, just realized that's the wrong board anyhow, we're using the at91sam9g20 . which machine type aligns with that?

**Comment by chipbagwell** [comment]
The at91sam9x5ek machine type is what should be generated in your build-atmel/tmp/deploy/images directory and works on the E10.

**Comment by angrydexterous** [comment]
does it require a newer version of uboot? also, i'm compiling off the master branch of meta-synapse.
right now using uboot from the older boards of 
U-Boot 2009.11 (Jun 29 2010 - 15:18:12)
and if so, do you have the nandwrite address of where the new uboot should go?
