### ISSUE TITLE
meta-synapse doesn't work

### ISSUE THREAD

**Issue by angrydexterous** [synapse-wireless/meta-synapse#8]
git clone git@git.synapse-wireless.com:octo/meta-synapse.git ${E10_SRC}/meta-synapse
fails

Cloning into '/home/vagrant/work/e10-2.x/meta-synapse'...
ssh: connect to host git.synapse-wireless.com port 22: Connection timed out
fatal: The remote end hung up unexpectedly

**Comment by cardoe** [comment]
I apologize I obviously didn't fix up all the URLs to point to GitHub.

**Comment by cardoe** [comment]
Also worth noting there's https://github.com/synapse-wireless/e10-yocto which is a repo manifest (think Android project's repo) for pulling down the specific versions of all the repos I tested with.
